{
  "swagger": "2.0",
  "info":
  {
    "description": "Ceci est la documentation de l'API Clara.",
    "version": "1.1.0",
    "title": "Clara API",
    "termsOfService": "https://clara.pole-emploi.fr/conditions-generales-d-utilisation",
    "contact":
    {
      "email": "bdavidxyz@gmail.com"
    },
    "license":
    {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "",
  "basePath": "/api/v1",
  "paths":
  {
   "/ping":
    {
      "get":
      {
        "tags": [
          "ping"
        ],
        "summary": "Ping the API, only returns a {\"status\":\"ok\"} when called",
        "description": "",
        "operationId": "getPing",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
              "status":"ok"
            } 
          },
          "429":
          {
            "description": "Too many request"
          },
          "500":
          {
            "description": "Internal server error"
          }
        }
      }
    },
    "/level3_filters":
    {
      "get":
      {
        "tags": [
          "filters"
        ],
        "summary": "Get all filters",
        "description": "",
        "operationId": "getAllFilters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        }],
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
              "level3_filters": [
                {
                  "name": "Gérer un problème d'alcool",
                  "description": "Savoir gérer un problème d'alcool",
                  "slug": "gerer-un-probleme-d-alcool",
                  "level2_filter": "gerer-une-addiction",
                  "level1_filter": "gerer-une-contrainte-personnelle"
                }
              ]
            }
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/filters":
    {
      "get":
      {
        "tags": [
          "filters"
        ],
        "summary": "Get all filters",
        "description": "",
        "operationId": "getAllFilters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        }],
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
              "filters": [
                {
                  "name": "Travailler en alternance",
                  "description": "Travailler en alternance",
                  "slug": "travailler-en-alternance"
                },
                {
                  "name": "S'informer sur les contrats spécifiques",
                  "description": "S'informer sur les contrats spécifiques",
                  "slug": "s-informer-sur-contrats-specifiques"
                },
                {
                  "name": "Travailler en Europe ou à l'international",
                  "description": "Travailler en Europe ou à l'international",
                  "slug": "travailler-a-l-international"
                }
              ]
            }
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/aids/detail/{aidSlug}":
    {
      "get":
      {
        "tags": [
          "aids"
        ],
        "summary": "Get Detail of an Aid",
        "description": "",
        "operationId": "getAidDetail",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        },
        {
          "in": "path",
          "name": "aidSlug",
          "type": "string",
          "description": "Slug of aid",
          "required": true
        }],
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example":{
              "aid": {
                "name": "Volontariat international (VI)",
                "what": "<p>La mission peut &ecirc;tre effectu&eacute;e en VIE (volontariat international en entreprise) ou en VIA (volontariat international en administration), au sein de diff&eacute;rentes structures (ambassades, universit&eacute;s et laboratoires, centres culturels, organisations non gouvernementales, ...).</p>",
                "slug": "vi-volontariat-international",
                "short_description": "Mission rémunérée qui permet d'avoir une première expérience à l'international",
                "how_much": "<p>Vous percevez une indemnit&eacute; d&#39;un montant pouvant aller de 1432 euros &agrave; 4784 euros nets.**</p>",
                "additionnal_conditions": "<p>Vous devez &nbsp;:</p>\r\n\r\n<p>- &ecirc;tre de nationalit&eacute; fran&ccedil;aise ou ressortissant(e) d&#39;un pays de l&#39;espace &eacute;conomique europ&eacute;en (EEE)</p>",
                "how_and_when": "<p>Vous devez enregistrer votre candidature par internet sur le site <a href=\"http://www.civiweb.com\" rel=\"noopener\" target=\"_blank\">Civiweb</a>.</p>",
                "limitations": "<p>** L&#39;indemnit&eacute; est fix&eacute;e par d&eacute;cret et varie selon le pays d&#39;affectation.</p>"
              }
            }
          },
          "404":
          {
            "description": "Not Found"
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/aids/eligible":
    {
      "get":
      {
        "tags": [
          "aids"
        ],
        "summary": "List all eligible aids",
        "description": "",
        "operationId": "getEligibleAids",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        },
        {
          "in": "query",
          "name": "disabled",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "spectacle",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "executive",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "diploma",
          "type": "string",
          "description": "level_1,level_2,level_3,level_4,level_5,level_below_5",
          "required": false
        },
        {
          "in": "query",
          "name": "category",
          "type": "string",
          "description": "categories_12345,other_categories",
          "required": false
        },
        {
          "in": "query",
          "name": "inscription_period",
          "type": "string",
          "description": "more_than_a_year,less_than_a_year,not_registered",
          "required": false
        },
        {
          "in": "query",
          "name": "allocation_type",
          "type": "string",
          "description": "ARE_ASP,ASS_AER_APS_ASFNE,RPS_RFPA_RFF_PENSION,RSA,AAH,none",
          "required": false
        },
        {
          "in": "query",
          "name": "monthly_allocation_value",
          "type": "integer",
          "description": "Estimated allocation per month",
          "required": false
        },
        {
          "in": "query",
          "name": "age",
          "type": "integer",
          "description": "Age of asker",
          "required": false
        },
        {
          "in": "query",
          "name": "location_citycode",
          "type": "string",
          "description": "Address : INSEE code of city",
          "required": false
        },
        {
          "in": "query",
          "name": "filters",
          "type": "string",
          "description": "comma-separated values of filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "level3_filters",
          "type": "string",
          "description": "comma-separated values of level3_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_filters",
          "type": "string",
          "description": "comma-separated values of custom_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_parent_filters",
          "type": "string",
          "description": "comma-separated values of custom parent filter's slug",
          "required": false
        }
      ],
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
                "asker": {
                  "zrr": "true",
                  "allocation_type": "RSA",
                  "age": "19",
                  "location_citycode": "02004"
                },
                "aids": [
                  {
                    "name": "Volontariat international (VI)",
                    "slug": "vi-volontariat-international",
                    "short_description": "Mission rémunérée qui permet d'avoir une première expérience à l'international",
                    "filters": [],
                    "level3_filters": ["gerer-des-problemes-d-argent"],
                    "contract_type": "emploi-international"
                  },
                  {
                    "name": "Contrat d'apprentissage",
                    "slug": "contrat-d-apprentissage",
                    "short_description": "Dispositif de formation initiale associant formation pratique en entreprise et enseignement théorique",
                    "filters": [
                      "travailler-en-alternance",
                      "aides-employeurs",
                      "se-former-valoriser-ses-competences"
                    ],
                    "level3_filters": [],
                    "contract_type": "contrat-en-alternance"
                  }
                ]
              }
          },
          "400":
          {
            "description": "Bad request"
          },
          "401":
          {
            "description": "Unauthorized"
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/aids/ineligible":
    {
      "get":
      {
        "tags": [
          "aids"
        ],
        "summary": "List all ineligible aids",
        "description": "",
        "operationId": "getIneligibleAids",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        },
        {
          "in": "query",
          "name": "disabled",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "spectacle",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "executive",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "diploma",
          "type": "string",
          "description": "level_1,level_2,level_3,level_4,level_5,level_below_5",
          "required": false
        },
        {
          "in": "query",
          "name": "category",
          "type": "string",
          "description": "categories_12345,other_categories",
          "required": false
        },
        {
          "in": "query",
          "name": "inscription_period",
          "type": "string",
          "description": "more_than_a_year,less_than_a_year,not_registered",
          "required": false
        },
        {
          "in": "query",
          "name": "allocation_type",
          "type": "string",
          "description": "ARE_ASP,ASS_AER_APS_ASFNE,RPS_RFPA_RFF_PENSION,RSA,AAH,none",
          "required": false
        },
        {
          "in": "query",
          "name": "monthly_allocation_value",
          "type": "integer",
          "description": "Estimated allocation per month",
          "required": false
        },
        {
          "in": "query",
          "name": "age",
          "type": "integer",
          "description": "Age of asker",
          "required": false
        },
        {
          "in": "query",
          "name": "location_citycode",
          "type": "string",
          "description": "Address : INSEE code of city",
          "required": false
        },
        {
          "in": "query",
          "name": "filters",
          "type": "string",
          "description": "comma-separated values of filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "level3_filters",
          "type": "string",
          "description": "comma-separated values of level3_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_filters",
          "type": "string",
          "description": "comma-separated values of custom_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_parent_filters",
          "type": "string",
          "description": "comma-separated values of custom parent filter's slug",
          "required": false
        }],
        
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
                "asker": {
                  "zrr": "true",
                  "allocation_type": "RSA",
                  "age": "19",
                  "location_citycode": "02004"
                },
                "aids": [
                  {
                    "name": "Volontariat international (VI)",
                    "slug": "vi-volontariat-international",
                    "short_description": "Mission rémunérée qui permet d'avoir une première expérience à l'international",
                    "filters": [],
                    "level3_filters": ["gerer-des-problemes-d-argent"],
                    "contract_type": "emploi-international"
                  },
                  {
                    "name": "Contrat d'apprentissage",
                    "slug": "contrat-d-apprentissage",
                    "short_description": "Dispositif de formation initiale associant formation pratique en entreprise et enseignement théorique",
                    "filters": [
                      "travailler-en-alternance",
                      "aides-employeurs",
                      "se-former-valoriser-ses-competences"
                    ],
                    "level3_filters": [],
                    "contract_type": "contrat-en-alternance"
                  }
                ]
              }
          },
          "400":
          {
            "description": "Bad request"
          },
          "401":
          {
            "description": "Unauthorized"
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/aids/uncertain":
    {
      "get":
      {
        "tags": [
          "aids"
        ],
        "summary": "List all uncertain aids",
        "description": "",
        "operationId": "getUncertainAids",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "header",
          "name": "Authorization",
          "type": "string",
          "description": "Bearer [your JWT token here]",
          "required": true
        },
        {
          "in": "query",
          "name": "disabled",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "spectacle",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "executive",
          "type": "string",
          "description": "true,false",
          "required": false
        },
        {
          "in": "query",
          "name": "diploma",
          "type": "string",
          "description": "level_1,level_2,level_3,level_4,level_5,level_below_5",
          "required": false
        },
        {
          "in": "query",
          "name": "category",
          "type": "string",
          "description": "categories_12345,other_categories",
          "required": false
        },
        {
          "in": "query",
          "name": "inscription_period",
          "type": "string",
          "description": "more_than_a_year,less_than_a_year,not_registered",
          "required": false
        },
        {
          "in": "query",
          "name": "allocation_type",
          "type": "string",
          "description": "ARE_ASP,ASS_AER_APS_ASFNE,RPS_RFPA_RFF_PENSION,RSA,AAH,none",
          "required": false
        },
        {
          "in": "query",
          "name": "monthly_allocation_value",
          "type": "integer",
          "description": "Estimated allocation per month",
          "required": false
        },
        {
          "in": "query",
          "name": "age",
          "type": "integer",
          "description": "Age of asker",
          "required": false
        },
        {
          "in": "query",
          "name": "location_citycode",
          "type": "string",
          "description": "Address : INSEE code of city",
          "required": false
        },
        {
          "in": "query",
          "name": "filters",
          "type": "string",
          "description": "comma-separated values of filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "level3_filters",
          "type": "string",
          "description": "comma-separated values of level3_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_filters",
          "type": "string",
          "description": "comma-separated values of custom_filter's slug",
          "required": false
        },
        {
          "in": "query",
          "name": "custom_parent_filters",
          "type": "string",
          "description": "comma-separated values of custom parent filter's slug",
          "required": false
        }],
        
        "responses":
        {
          "200":
          {
            "description": "Found",
            "example": {
                "asker": {
                  "zrr": "true",
                  "allocation_type": "RSA",
                  "age": "19",
                  "location_citycode": "02004"
                },
                "aids": [
                  {
                    "name": "Volontariat international (VI)",
                    "slug": "vi-volontariat-international",
                    "short_description": "Mission rémunérée qui permet d'avoir une première expérience à l'international",
                    "filters": [],
                    "level3_filters": ["gerer-des-problemes-d-argent"],
                    "contract_type": "emploi-international"
                  },
                  {
                    "name": "Contrat d'apprentissage",
                    "slug": "contrat-d-apprentissage",
                    "short_description": "Dispositif de formation initiale associant formation pratique en entreprise et enseignement théorique",
                    "filters": [
                      "travailler-en-alternance",
                      "aides-employeurs",
                      "se-former-valoriser-ses-competences"
                    ],
                    "level3_filters": [],
                    "contract_type": "contrat-en-alternance"
                  }
                ]
              }

          },
          "400":
          {
            "description": "Bad request"
          },
          "401":
          {
            "description": "Unauthorized"
          },
          "500":
          {
            "description": "Internal server error"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    },
    "/user_token":
    {
      "post":
      {
        "tags": [
          "user"
        ],
        "summary": "Ask to authenticate",
        "description": "",
        "operationId": "user_token",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
        {
          "in": "body",
          "name": "body",
          "description": "Credential for authentication",
          "required": true,
          "schema":
          {
            "$ref": "#/definitions/Auth"
          }
        }],
        "responses":
        {
          "201":
          {
            "description": "Found",
            "example": {
              "jwt": "averylongtoken.that-respect-jwt-standard"
            }
          },
          "404":
          {
            "description": "Not found"
          },
          "429":
          {
            "description": "Too many request"
          }
        }
      }
    }
  },
  "definitions":
  {
    "Auth":
    {
      "type": "object",
      "properties":
      {
        "auth":
        {
          "type": "object",
          "properties":
          {
            "email":
            {
              "type": "string"
            },
            "password":
            {
              "type": "string"
            }
          }
        }
      }
    },
    "ApiResponse":
    {
      "type": "object",
      "properties":
      {
        "code":
        {
          "type": "integer",
          "format": "int32"
        },
        "type":
        {
          "type": "string"
        },
        "message":
        {
          "type": "string"
        }
      }
    }
  }
}
